sudo: required
services:
  - docker
language: go
go:
  - "1.11"
env:
  - GOOS=linux CGO_ENABLED=0

addons:
  apt:
    packages:
      - docker-ce

install: true

before_script:
  - docker network ls
  - docker -v
  - docker-compose -v

script:
  - go test -v ./...
