sudo: required
services:
  - docker
language: go
go:
  - "1.11"
env:
  - GOOS=linux CGO_ENABLED=0

install: true

before_script:
  - docker network ls
  - docker network prune

script:
  - go test -v ./...
